# Generated by Django 2.0.9 on 2019-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dajia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='实名认证时间'),
        ),
    ]
