# Generated by Django 2.0.9 on 2019-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dajia', '0002_auto_20190405_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='cutting',
            options={'verbose_name': '砍价', 'verbose_name_plural': '砍价'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': '商家', 'verbose_name_plural': '商家'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': '期表', 'verbose_name_plural': '期表'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterModelOptions(
            name='steam',
            options={'verbose_name': '小团', 'verbose_name_plural': '小团'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'get_latest_by': 'time', 'verbose_name': '团队', 'verbose_name_plural': '团队'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=50, verbose_name='微信头像'),
        ),
    ]
