# Generated by Django 2.0.9 on 2019-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dajia', '0003_auto_20190405_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名'),
        ),
    ]
