# Generated by Django 2.0.9 on 2019-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dajia', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='微信头像'),
        ),
    ]
